### ISSUE TITLE
Allow convention configuration

### ISSUE THREAD

**Issue by andre-filho** [andre-filho/commit-helper#15]
Users must be allowed to add optional fields in the commiter.yml file, such as a body field, footer and such. To understand more visit http://karma-runner.github.io/2.0/dev/git-commit-msg.html

**Comment by andre-filho** [comment]
Support something like:
```yaml
# commiter.yml
convention: angular
context: optional
body: optional
footer: optional
```
